endpoints:
  - path: "/api/provider/openai/v1/chat/completions"
    target_url: "https://api-key.info/v1/chat/completions"
    method: "POST"
    response_type: "stream"
    custom_headers: {}
    forward_request_headers:
      - "authorization"
      - "content-type" 
      - "user-agent"
      - "accept"
      - "accept-encoding"
    forward_response_headers:
      - "content-type"
      - "cache-control"
    enabled: true

  - path: "/api/provider/anthropic/v1/messages"
    target_url: "https://api-key.info/v1/messages"
    method: "POST"
    response_type: "stream"
    custom_headers: {}
    forward_request_headers:
      - "authorization"
      - "content-type"
      - "user-agent" 
      - "accept"
      - "accept-encoding"
      - "anthropic-version"
      - "x-api-key"
    forward_response_headers:
      - "content-type"
      - "cache-control"
    enabled: true

  - path: "/api/tab/llm-proxy"
    target_url: "https://ampcode.com/api/tab/llm-proxy"
    method: "POST"
    response_type: "sse"
    custom_headers: {}
    forward_request_headers:
      - "authorization"
      - "user-agent"
      - "x-amp-feature"
      - "accept-language"
      - "sec-fetch-mode"
    forward_response_headers:
      - "alt-svc"
      - "content-security-policy"
      - "fireworks-backend-host"
      - "fireworks-cached-prompt-tokens"
      - "fireworks-deployment"
      - "fireworks-generation-queue-duration"
      - "fireworks-num-concurrent-requests"
      - "fireworks-prefill-duration"
      - "fireworks-prefill-queue-duration"
      - "fireworks-prompt-tokens"
      - "fireworks-sampling-options"
      - "fireworks-server-time-to-first-token"
      - "fireworks-speculation-matched-tokens"
      - "fireworks-speculation-prompt-tokens"
      - "fireworks-tokenizer-duration"
      - "fireworks-tokenizer-queue-duration"
    enabled: true